server:
  port: 8081
  servlet:
    context-path: /ems-jsp #指定項目名
    jsp:
      init-parameters:
        development: true #開啟jsp模板開發模式


#配置jsp模板
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems-jsp?characterEncoding=UTF-8
    username: root
    password: 123456

#配置mybatis
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity

#配置日誌使用
logging:
  level:
    root: info
    com.baizhi: debug
